# <font color='blue'>Data Science Academy - Python Fundamentos - Capítulo 8</font>

## Download: http://github.com/dsacademybr

In [1]:
# Versão da Linguagem Python
from platform import python_version
print('Versão da Linguagem Python Usada Neste Jupyter Notebook:', python_version())

Versão da Linguagem Python Usada Neste Jupyter Notebook: 3.7.6


### Exercícios Sobre Módulos Python Para Análise de Dados

### ****** ATENÇÃO ******
### Alguns dos exercícios podem requerer pesquisa adicional na documentação dos pacotes. Pesquise!

### Exercício 1

In [19]:
# Crie um array NumPy com 1000000 e uma lista com 1000000.
# Multiplique cada elemento do array e da lista por 2 e calcule o tempo de execução com cada um dos objetos (use %time).
# Qual objeto oferece melhor performance, array NumPy ou lista?

import numpy as np

limite = 1000000

arr1 = [x for x in range(limite)]
arr2 = np.array(arr1)

print(type(arr1))
print(type(arr2))
#print(arr1)
#print(arr2)

%time arr1 * 2
%time arr2 * 2


print("O tempo de multiplicação com o numpy é bem menor.")



<class 'list'>
<class 'numpy.ndarray'>
CPU times: user 10.8 ms, sys: 3.85 ms, total: 14.7 ms
Wall time: 14.6 ms
CPU times: user 2.17 ms, sys: 0 ns, total: 2.17 ms
Wall time: 1.86 ms
O tempo de multiplicação com o numpy é bem menor.


### Exercício 2

In [24]:
# Exercício 2
# Crie um array de 10 elementos
# Altere o valores de todos os elementos dos índices 5 a 8 para 0

arr = np.random.rand(10)
arr[5:9] = 0
arr


array([0.6399377 , 0.68381081, 0.73776661, 0.43863615, 0.63201804,
       0.        , 0.        , 0.        , 0.        , 0.90997811])

### Exercício 3

In [29]:
# Crie um array de 3 dimensões e imprima a dimensão 1 

arr = np.arange(27).reshape(3,3,3)
arr[0]


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### Exercício 4

In [37]:
# Crie um array de duas dimensões (matriz).
# Imprima os elementos da terceira linha da matriz
# Imprima todos os elementos da primeira e segunda linhas e segunda e terceira colunas

arr = np.arange(20).reshape(4,5)
print(arr)
linhas = [0,1]
colunas = [1,2]
for l in linhas:
    for c in colunas:
        print("Elemento da linha %d e coluna %d: %d" % (l+1,c+1,arr[l,c]))


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
Elemento da linha 1 e coluna 2: 1
Elemento da linha 1 e coluna 3: 2
Elemento da linha 2 e coluna 2: 6
Elemento da linha 2 e coluna 3: 7


### Exercício 5

In [38]:
# Calcule a transposta da matriz abaixo
arr = np.arange(15).reshape((3, 5))
arr.transpose()

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

### Exercício 6

In [42]:
# Considere os 3 arrays abaixo
# Retorne o valor do array xarr se o valor for True no array cond. Caso contrário, retorne o valor do array yarr.
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])
result = np.zeros(len(cond))
for i,c in enumerate(cond):
    if c:
        result[i] = xarr[i]
    else:
        result[i] = yarr[i]
print(result)

[1.1 2.2 1.3 1.4 2.5]


### Exercício 7

In [47]:
# Crie um array A com 10 elementos e salve o array em disco com a extensão npy
# Depois carregue o array do disco no array B

A = np.arange(10)
print(A)
np.save("A.npy",A)
B = np.load("A.npy")
print(B)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


### Exercício 8

In [48]:
# Considerando a série abaixo, imprima os valores únicos na série
import pandas as pd
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c', 'a', 'b'])
print(obj.unique())

['c' 'a' 'd' 'b']


### Exercício 9

In [58]:
# Considerando o trecho de código que conecta em uma url na internet, imprima o dataframe conforme abaixo.
import requests
url = 'https://api.github.com/repos/pandas-dev/pandas/issues'
resp = requests.get(url)


import pandas as pd

df = pd.DataFrame(resp.json())
df = pd.DataFrame(df,columns = ["number","title","labels","state"])
df

number                                              title  \
0    35165                                  Fixed apply_index   
1    35164   Infer compression if file extension is uppercase   
2    35163                     CI: update to isort 5 (#35134)   
3    35162  ENH: should pandas.core.arrays.Categorical hav...   
4    35161  BUG: KeyError on MultiIndex when filtering by ...   
5    35160                     CI: add sql tests back to py36   
6    35158             BUG: datetime total_seconds inaccurate   
7    35157                        July 2020 Developer Meeting   
8    35154  REF: remove always-UTC arg from tz_convert, tz...   
9    35152  BUG: transform with nunique should have dtype ...   
10   35150  BUG: pd.crosstab fails when passed multiple co...   
11   35149                                 ASV: tslibs.fields   
12   35148  CI: MacPython failing test_consistency_with_wi...   
13   35147  CI: MacPython failing TestPandasContainer.test...   
14   35144  BUG: pd.crosstab fails when passed multiple co...   
15   35142                         improved exception message   
16   35140           Fix regression on datetime in MultiIndex   
17   35138  CI/DOC: autodoc failures for DataFrame.sparse ...   
18   35137    BUG:sort_values in groupby make some value lost   
19   35135                 BUG:  .corr() values higher than 1   
20   35134                              CI: Update to isort 5   
21   35132  BUG: Passing `level=` to `DataFrame.reindex` f...   
22   35131  ENH: Identify numpy-like zero-dimensional arra...   
23   35130  BUG: transform with nunique should have dtype ...   
24   35129              support binary file handles in to_csv   
25   35127  ENH: make is_list_like handle non iterable num...   
26   35126                      BUG: unexpected cut() results   
27   35123  BUG: pandas does not build on AIX - when using...   
28   35122                 CLN: remove kwargs in Index.format   
29   35121              TST add test case for drop_duplicates   

                                               labels state  
0   [{'id': 87485152, 'node_id': 'MDU6TGFiZWw4NzQ4...  open  
1                                                  []  open  
2                                                  []  open  
3   [{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...  open  
4   [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
5   [{'id': 48070600, 'node_id': 'MDU6TGFiZWw0ODA3...  open  
6   [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
7   [{'id': 2187005593, 'node_id': 'MDU6TGFiZWwyMT...  open  
8   [{'id': 211029535, 'node_id': 'MDU6TGFiZWwyMTE...  open  
9   [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
10  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
11  [{'id': 732775912, 'node_id': 'MDU6TGFiZWw3MzI...  open  
12                                                 []  open  
13  [{'id': 563047854, 'node_id': 'MDU6TGFiZWw1NjM...  open  
14  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
15  [{'id': 42670965, 'node_id': 'MDU6TGFiZWw0MjY3...  open  
16  [{'id': 2822098, 'node_id': 'MDU6TGFiZWwyODIyM...  open  
17  [{'id': 48070600, 'node_id': 'MDU6TGFiZWw0ODA3...  open  
18  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
19  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
20  [{'id': 48070600, 'node_id': 'MDU6TGFiZWw0ODA3...  open  
21  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
22  [{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...  open  
23  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
24                                                 []  open  
25                                                 []  open  
26  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
27  [{'id': 129350, 'node_id': 'MDU6TGFiZWwxMjkzNT...  open  
28  [{'id': 211029535, 'node_id': 'MDU6TGFiZWwyMTE...  open  
29  [{'id': 2822342, 'node_id': 'MDU6TGFiZWwyODIyM...  open

### Exercício 10

In [95]:
# Crie um banco de dados no SQLite, crie uma tabela, insira registros, 
# consulte a tabela e retorne os dados em dataframe do Pandas

import os
os.remove("dados.db") if os.path.exists("dados.db") else None

import sqlite3

con = sqlite3.connect("dados.db")
cur = con.cursor()

sql = "create table dados (id integer primary key autoincrement, x integer, y integer)"
cur.execute(sql)

sql = "insert into dados (x,y) values (?,?)"

dados = np.arange(20).reshape(10,2)

for d in dados:
    cur.execute(sql,(int(d[0]),int(d[1])))

con.commit()



In [96]:
sql = "select * from dados"

cur.execute(sql)
dados_banco = cur.fetchall()

df = pd.DataFrame(columns = ["x","y"])


for linha in dados_banco:
    #print(linha)
    df = df.append({'x':linha[1],'y':linha[2]},ignore_index=True)

print(df)

con.close()

    x   y
0   0   1
1   2   3
2   4   5
3   6   7
4   8   9
5  10  11
6  12  13
7  14  15
8  16  17
9  18  19


# Fim

### Obrigado - Data Science Academy - <a href="http://facebook.com/dsacademybr">facebook.com/dsacademybr</a>